# Generated by Django 4.2.7 on 2023-12-09 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0012_cart_transaction_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='variation',
        ),
    ]
