# Generated by Django 4.1 on 2023-12-12 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0018_alter_cart_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='is_expired',
        ),
    ]
