# Generated by Django 4.1 on 2023-12-14 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0020_coupon_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
