# Generated by Django 4.1 on 2023-12-14 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0021_alter_coupon_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
    ]
