# Generated by Django 4.2.4 on 2023-11-20 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin_panel', '0008_size_productvariance'),
        ('carts', '0004_alter_cart_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Whishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='custom_admin_panel.product')),
            ],
        ),
    ]
