# Generated by Django 4.2.4 on 2023-11-20 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
       
        ('carts', '0006_whishlist_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whishlist',
            name='product',
        ),
        migrations.AddField(
            model_name='whishlist',
            name='products',
            field=models.ManyToManyField(related_name='wishlist_products', to='custom_admin_panel.product'),
        ),
    ]
