# Generated by Django 4.2.4 on 2023-11-20 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
       
        ('carts', '0007_remove_whishlist_product_whishlist_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whishlist',
            name='products',
        ),
        migrations.AddField(
            model_name='whishlist',
            name='products',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='custom_admin_panel.product'),
            preserve_default=False,
        ),
    ]
