# Generated by Django 4.2.7 on 2023-12-04 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0009_remove_whishlist_products_whishlist_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('COD', 'Cash on Delivery'), ('RAZ', 'Paid With Razorpay')], max_length=20, null=True),
        ),
    ]
