# Generated by Django 4.2.7 on 2023-12-06 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0010_alter_cart_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='delivery_status',
            field=models.CharField(choices=[('PL', 'Order placed'), ('DS', 'Dispatched'), ('SH', 'Shipped'), ('OFD', 'Out for Delivery'), ('D', 'Delivered'), ('CN', 'Order Cancelled'), ('RT', 'Returned'), ('C', 'Cart Added')], default='C', max_length=3),
        ),
    ]
