# Generated by Django 4.2.7 on 2023-12-09 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0011_alter_cartitem_delivery_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='transaction_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
