# Generated by Django 4.2.7 on 2023-12-10 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin_panel', '0019_coupon_delete_productvariance_delete_size'),
        ('carts', '0015_alter_cartitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='custom_admin_panel.coupon'),
        ),
    ]
