# Generated by Django 4.1 on 2023-12-14 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0019_remove_coupon_is_expired'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
