# Generated by Django 4.1 on 2023-12-31 13:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0024_alter_coupon_valid_till'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='valid_till',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 30, 13, 33, 19, 733223, tzinfo=datetime.timezone.utc)),
        ),
    ]
