# Generated by Django 4.1 on 2024-01-01 09:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0025_alter_coupon_valid_till'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='address_lines',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='full_name',
            field=models.CharField(default='default_value', max_length=255),
        ),
        migrations.AddField(
            model_name='cart',
            name='mobile',
            field=models.CharField(default='default_value', max_length=15),
        ),
        migrations.AddField(
            model_name='cart',
            name='pin_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product_description_at_order',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product_price_at_order',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product_stock_at_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='valid_till',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 31, 9, 33, 49, 24426, tzinfo=datetime.timezone.utc)),
        ),
    ]
