# Generated by Django 4.1 on 2024-01-01 10:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0026_cart_address_lines_cart_city_cart_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='valid_till',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 31, 10, 16, 9, 206171, tzinfo=datetime.timezone.utc)),
        ),
    ]
