# Generated by Django 4.1 on 2024-01-01 11:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0027_alter_coupon_valid_till'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cart_items_total_at_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cart',
            name='cart_total_at_order',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='valid_till',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 31, 11, 7, 53, 820096, tzinfo=datetime.timezone.utc)),
        ),
    ]
