# Generated by Django 4.1 on 2024-01-02 09:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0028_cart_cart_items_total_at_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='valid_till',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 1, 9, 26, 8, 308962, tzinfo=datetime.timezone.utc)),
        ),
    ]
