# Generated by Django 4.1 on 2024-01-02 09:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0030_alter_coupon_valid_till'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='valid_till',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 1, 9, 40, 51, 200483, tzinfo=datetime.timezone.utc)),
        ),
    ]
