# Generated by Django 4.1 on 2024-01-03 06:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0031_alter_coupon_valid_till'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='valid_till',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 2, 6, 42, 45, 72819, tzinfo=datetime.timezone.utc)),
        ),
    ]
