# Generated by Django 4.2.7 on 2023-11-30 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_offercategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offercategory',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
