# Generated by Django 4.2.7 on 2023-11-30 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_offer_active_offercategory_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='date_start',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='offercategory',
            name='date_start',
            field=models.DateTimeField(),
        ),
    ]
