# Generated by Django 4.2.7 on 2023-11-30 09:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_offer_date_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='date_start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='offercategory',
            name='date_start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
