# Generated by Django 4.2.4 on 2023-11-22 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
