# Generated by Django 4.2.7 on 2023-12-11 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_wallet_remove_orderitem_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='card_id',
        ),
    ]
