# Generated by Django 4.1 on 2023-12-31 11:26

from django.db import migrations, models
from datetime import datetime

current_datetime = datetime.now().strftime('%Y-%m-%dT%H:%M:%S')



class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0007_wallet_wallet_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=current_datetime),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='is_for_orders',
            field=models.BooleanField(default=False),
        ),
    ]
