# Generated by Django 4.1 on 2023-12-31 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
