# Generated by Django 4.1 on 2024-01-03 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin_panel', '0002_product_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='version',
        ),
    ]
