# Generated by Django 4.2.4 on 2023-11-08 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin_panel', '0005_remove_product_image_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='adminside\x07ssets\\images\\solo_images\x07thletics'),
        ),
    ]
