# Generated by Django 4.2.4 on 2023-11-08 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin_panel', '0006_alter_productimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='adminside/assets/images/solo_images/athletics'),
        ),
    ]
