# Generated by Django 4.2.7 on 2023-12-01 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin_panel', '0013_category_offer_product_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_with_offer',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
