# Generated by Django 4.2.7 on 2023-12-02 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin_panel', '0014_product_price_with_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price_with_offer',
        ),
    ]
