# Generated by Django 4.2.7 on 2023-12-05 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin_panel', '0016_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
