# Generated by Django 4.2.7 on 2023-12-05 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_offer_discount_percentage'),
        ('custom_admin_panel', '0017_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category_offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.offercategory'),
        ),
    ]
