# Generated by Django 4.2.7 on 2023-12-10 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0017_coupon_alter_cart_coupon'),
        ('custom_admin_panel', '0019_coupon_delete_productvariance_delete_size'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
